services:
  db:
    image: postgres:15
    container_name: postgres_replace
    restart: always
    environment:
      POSTGRES_DB: replace_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: always
    depends_on:
      - db
    environment:
      DB_NAME: replace_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: bash -c "python seeder_main.py && uvicorn main:app --host 0.0.0.0 --port 8000"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: http://localhost:8000/api
    container_name: frontend
    ports:
      - "3000:80"

volumes:
  postgres_data:
